# Generated by Django 3.1.6 on 2023-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_connection_date_alter_connection_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook'), ('signal', 'Signal'), ('text', 'Text'), ('phonecall', 'Phonecall'), ('discord', 'Discord')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
