# Generated by Django 3.1.6 on 2023-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20230610_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook'), ('signal', 'Signal'), ('text', 'Text'), ('phonecall', 'Phonecall'), ('discord', 'Discord'), ('linkedin', 'LinkedIn')], default='email', max_length=20),
        ),
    ]
