# Generated by Django 3.1.6 on 2023-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20230610_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='next_connection',
            field=models.DateField(blank=True),
        ),
    ]
