# Generated by Django 4.2.2 on 2023-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_connection_contact_alter_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
