# Generated by Django 4.2.2 on 2023-12-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_connection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
