# Generated by Django 4.2.2 on 2024-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_add_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
