# Generated by Django 4.2.2 on 2024-09-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_connection_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
