# Generated by Django 4.2.2 on 2025-06-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_connection_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook'), ('signal', 'Signal'), ('text', 'Text'), ('phonecall', 'Phonecall'), ('discord', 'Discord'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('slack', 'Slack')], default='email', max_length=20),
        ),
    ]
